apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-new
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"